services:
  nodebb:
    container_name: forum
    image: mute/forum:${TAG}
    restart: unless-stopped
    ports:
      - '4567:4567'
    depends_on:
      - mongo
      - redis
    volumes:
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-config:/opt/config

  mongo:
    hostname: mongo
    container_name: mongo
    image: 'mongo:8.2.5-noble'
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo-data:/data/db
      - mongo-backup:/data/backup
      - ./install/docker/mongodb-user-init.js:/docker-entrypoint-initdb.d/user-init.js

  redis:
    container_name: redis
    image: redis:8.6.1-alpine
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes', '--loglevel', 'warning']
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/mongo/data
  
  mongo-backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/backup/mongo

  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/database/redis

  nodebb-build:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/build

  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/public/uploads

  nodebb-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./.docker/config